<a href="https://colab.research.google.com/github/sana9524/Farha0952/blob/main/Python_Day1_Feb_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('My name is brand')


My name is brand


In [ ]:
x=20

In [ ]:
x

20

In [ ]:
type(x)

int

In [ ]:
z=13.5

type(z)

In [ ]:
type(z)

float

In [ ]:
# Arithmetic operation
x= 20
y=10
z=x+y
print(z)

30


In [ ]:
x=100
y=80
z=x-y
print(z)

20


In [ ]:
20+10;100-80; 990/99;85*10

850

In [ ]:
print(20+10)
print(100-80)
print(990/99)
print(85*10)

30
20
10.0
850


In [ ]:
import math

In [ ]:
math.sqrt(64)


8.0

In [ ]:
list=['Brad', '20','30','sana']
print(list)

['Brad', '20', '30', 'sana']


In [ ]:
list[1]

'20'

In [ ]:
list[1]=40
list

['Brad', 40, '30', 'sana']

test=4>1
test


In [2]:
type(test)

bool

In [7]:
sample1=7>6
sample2= 6>8
sample1 & sample2
sample3 =5>1
sample4=6>3

In [9]:
### Loop
i=0
while i<=10:
  print(i)
  i=i+1
print('python is easy lang')



0
1
2
3
4
5
6
7
8
9
10
python is easy lang


In [10]:
i=0
while i<=10:
  print(i)
print('python is easy lang')

Streaming output truncated to the last 5000 lines.
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

KeyboardInterrupt: ignored

In [12]:
range(6)

range(0, 6)

In [11]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [15]:
for i in range(6):
  print(i)
  print('python is good')
print('python is good')

0
python is good
1
python is good
2
python is good
3
python is good
4
python is good
5
python is good
python is good


In [17]:
import numpy as np
from numpy.random import randn

In [23]:
x=randn()
if (x > 1):
  print('greater than one')

In [28]:
import numpy as np
from numpy.random import randn
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

1.3126140637803043
greater than 1


In [31]:
result=None
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

1.30613063556728
greater than 1


In [34]:
result=None
x=randn()
if x>1:
  result="greater than 1"
elif x<-1:
  reult="less then -1"
else:
  result="Between -1 and 1"
print(x)
print(result)

1.4927801958699085
greater than 1


In [37]:
mylist=[1,2,3,4]
print(mylist)
type(mylist)

[1, 2, 3, 4]


list

In [45]:
list(range(1,51,3))
list1=list(range(1,51,3))
list1[1]
list1[-1]

49

In [46]:
letters=['A','B','C','D','E','F','H', 'I','J']
letters

['A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'J']

In [47]:
letters[1:8:2]

['B', 'D', 'F', 'I']

In [48]:
letters[-9:-1:2]

['A', 'C', 'E', 'H']

In [50]:
letters[::3]

['A', 'D', 'H']

In [49]:
letters[1:2]

['B']

In [51]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'H']

In [52]:
letters[7:]

['I', 'J']

In [55]:
letters[-1]

'J'

In [56]:
letters[::-1]

['J', 'I', 'H', 'F', 'E', 'D', 'C', 'B', 'A']

In [59]:
letters[1:6:-1]

[]

In [58]:
letters[6:1:-1]

['H', 'F', 'E', 'D', 'C']

In [66]:
tuple1=(12,13,16)
tuple1[1]
tuple1[2]=43

TypeError: ignored

In [65]:
list3=[1,2,3]
list3[1]=5
list3

[1, 5, 3]

In [67]:
range(30,41l)

range(30, 41)

In [69]:
list(range(30,41))

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]

In [70]:
mylist1=list(range(30,41))

In [72]:
import numpy as np
list$-['a',20,80,70,'true']
np.array(list$)

SyntaxError: ignored

In [73]:
b=np.array([2345,6789,8976,1456,-1234])
b.mean()

3666.4

In [74]:
b

array([ 2345,  6789,  8976,  1456, -1234])

In [77]:
b[::2]

array([ 2345,  8976, -1234])

In [78]:
b[1:2]

array([6789])

In [79]:
c=b[2:4]

In [80]:
c

array([8976, 1456])

In [82]:
c[:]

array([8976, 1456])

In [81]:
c[:]

array([8976, 1456])

In [84]:
c[:]=222

In [85]:
b

array([ 2345,  6789,   222,   222, -1234])

In [86]:
### dictionary
dic={'Indexes0': 'Emp No','Indexe1':'EmpName','Indexe2':'Salary'}
dic


{'Indexes0': 'Emp No', 'Indexe1': 'EmpName', 'Indexe2': 'Salary'}

In [87]:
dic['Indexe2']

'Salary'

In [ ]:
###Pandas
